network:
    version: 2
    ethernets:
        enp8s0:
            dhcp4: false
            addresses: [10.0.3.170/22]
            gateway4: 10.0.3.254
            nameservers:
              addresses: [8.8.8.8, 10.0.3.254]

    vlans:
        enp8s0.10:
            id: 10
            link: enp8s0
        enp8s0.20:
            id: 20
            link: enp8s0
        enp8s0.30:
            id: 30
            link: enp8s0
        enp8s0.40:
            id: 40
            link: enp8s0
    bridges:
        br-mgmt:
            addresses:
            - 172.29.236.10/22
            interfaces:
            - enp8s0.10
            mtu: 1500
        br-storage:
            addresses:
            - 172.29.244.10/22
            interfaces:
            - enp8s0.20
            mtu: 1500
        br-vxlan:
            addresses:
            - 172.29.240.10/22
            interfaces:
            - enp8s0.30
            mtu: 1500
        br-ext:
            addresses:
            - 10.0.3.170/22
            interfaces:
            - enp8s0
            routes:
              - to: 0.0.0.0/0
                via: 10.0.3.254
            nameservers:
                addresses:
                - 10.0.3.254
            mtu: 1500
        br-vlan:
            interfaces:
            - enp8s0.40
            mtu: 1500
